application: summer-t 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: cs.application
  secure: always
- url: /blog/.*
  script: blog.application

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
